# Generated by Django 5.0.6 on 2024-05-26 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WikiPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="SecretCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="wiki.secretcategory",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Secret",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("categories", models.ManyToManyField(related_name="categories", to="wiki.secretcategory")),
                ("known_to", models.ManyToManyField(related_name="known_to", to="wiki.wikipage")),
            ],
        ),
        migrations.CreateModel(
            name="Revision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "page_type",
                    models.CharField(
                        choices=[("page", "Page"), ("character", "Character")], default="page", max_length=20
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True, null=True)),
                ("message", models.TextField(max_length=255)),
                (
                    "read",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("members", "Members only"),
                            ("editors", "Editors only"),
                            ("owner", "Owner only"),
                            ("admin", "Admins only"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "write",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("members", "Members only"),
                            ("editors", "Editors only"),
                            ("owner", "Owner only"),
                            ("admin", "Admins only"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("is_latest", models.BooleanField(default=True)),
                (
                    "editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="wiki.wikipage"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="wiki.wikipage"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="revision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest", True)), fields=("slug", "page"), name="unique_page_slug"
            ),
        ),
    ]
