# Generated by Django 5.0.6 on 2024-05-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0002_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="revision",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
