# Generated by Django 5.0.6 on 2024-05-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0003_revision_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wikipage",
            name="title",
        ),
    ]
