# Generated by Django 5.0.6 on 2024-05-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0007_revision_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="revision",
            name="read",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("members", "Members only"),
                    ("editors", "Editors only"),
                    ("owner", "Owner only"),
                    ("admin", "Admins only"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="revision",
            name="write",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("members", "Members only"),
                    ("editors", "Editors only"),
                    ("owner", "Owner only"),
                    ("admin", "Admins only"),
                ],
                default="public",
                max_length=20,
            ),
        ),
    ]
