# Generated by Django 5.0.6 on 2024-05-23 14:10

from django.db import migrations, models
from slugify import slugify


def set_default_slugs(apps, schema_editor):
    rev = apps.get_model('wiki', 'Revision')
    for revision in rev.objects.all():
        revision.slug = slugify(revision.title)
        revision.save()


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0008_revision_read_revision_write"),
    ]

    operations = [
        migrations.AddField(
            model_name="revision",
            name="slug",
            field=models.CharField(default="SLUG", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_slugs),
    ]
