# Generated by Django 5.0.6 on 2024-05-23 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0009_revision_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="revision",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="wiki.wikipage",
            ),
        ),
    ]
