# Generated by Django 5.0.6 on 2024-05-23 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0010_revision_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="revision",
            name="message",
            field=models.TextField(default="Revision", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="revision",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="wiki.wikipage",
            ),
        ),
    ]
