# Generated by Django 5.0.6 on 2024-05-25 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0012_revision_is_latest_alter_revision_parent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="revision",
            name="unique_page_slug",
        ),
        migrations.AddConstraint(
            model_name="revision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest", True)), fields=("slug", "page"), name="unique_page_slug"
            ),
        ),
    ]
