# Generated by Django 5.0.6 on 2024-05-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0013_remove_revision_unique_page_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipage",
            name="type",
            field=models.CharField(choices=[("page", "Page")], default="page", max_length=20),
        ),
    ]
