# Generated by Django 5.0.6 on 2024-05-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0014_wikipage_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wikipage",
            name="type",
        ),
        migrations.AddField(
            model_name="revision",
            name="page_type",
            field=models.CharField(
                choices=[("page", "Page"), ("character", "Character")], default="page", max_length=20
            ),
        ),
    ]
