volumes:
  scarletbanner_production_postgres_data: {}
  scarletbanner_production_postgres_data_backups: {}
  scarletbanner_production_redis_data: {}
  scarletbanner_production_traefik: {}
  scarletbanner_production_django_media: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: scarletbanner_production_django
    volumes:
      - scarletbanner_production_django_media:/app/scarletbanner/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.postgres
      - ./.envs/.production/.django
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: scarletbanner_production_postgres
    volumes:
      - scarletbanner_production_postgres_data:/var/lib/postgresql/data
      - scarletbanner_production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: scarletbanner_production_traefik
    depends_on:
      - django
    volumes:
      - scarletbanner_production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:5555:5555'

  redis:
    image: redis:6
    container_name: scarletbanner_production_redis
    volumes:
      - scarletbanner_production_redis_data:/data

  celeryworker:
    <<: *django
    image: scarletbanner_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: scarletbanner_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: scarletbanner_production_flower
    command: /start-flower

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: scarletbanner_local_nginx
    depends_on:
      - django
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf
      - ../scarletbanner-design:/design
      - scarletbanner_production_django_media:/usr/share/nginx/media:ro
