# Generated by Django 5.0.6 on 2024-05-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="secretcategory",
            options={"verbose_name": "Secret category", "verbose_name_plural": "Secret categories"},
        ),
        migrations.AlterField(
            model_name="secret",
            name="categories",
            field=models.ManyToManyField(related_name="secrets", to="wiki.secretcategory"),
        ),
        migrations.AlterField(
            model_name="secret",
            name="known_to",
            field=models.ManyToManyField(blank=True, related_name="secrets_known", to="wiki.wikipage"),
        ),
    ]
