# Generated by Django 5.0.6 on 2024-05-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpage",
            name="read",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("members", "Members"),
                    ("editors", "Editors"),
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalpage",
            name="write",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("members", "Members"),
                    ("editors", "Editors"),
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="read",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("members", "Members"),
                    ("editors", "Editors"),
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="write",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("members", "Members"),
                    ("editors", "Editors"),
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                ],
                default="public",
                max_length=20,
            ),
        ),
    ]
