# Generated by Django 5.0.6 on 2024-05-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0002_alter_secretcategory_options_alter_secret_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revision",
            name="page_type",
            field=models.CharField(
                choices=[("page", "Page"), ("template", "Template"), ("character", "Character")],
                default="page",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="read",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("members", "Members"),
                    ("editors", "Editors"),
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="write",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("members", "Members"),
                    ("editors", "Editors"),
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                ],
                default="public",
                max_length=20,
            ),
        ),
    ]
