# Generated by Django 5.0.6 on 2024-06-01 00:45

import scarletbanner.wiki.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0003_alter_historicalpage_slug_alter_page_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpage",
            name="read",
            field=models.IntegerField(
                choices=[(100, 100), (300, 300), (600, 600), (999, 999)],
                default=scarletbanner.wiki.enums.PermissionLevel["PUBLIC"],
            ),
        ),
        migrations.AlterField(
            model_name="historicalpage",
            name="write",
            field=models.IntegerField(
                choices=[(100, 100), (300, 300), (600, 600), (999, 999)],
                default=scarletbanner.wiki.enums.PermissionLevel["PUBLIC"],
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="read",
            field=models.IntegerField(
                choices=[(100, 100), (300, 300), (600, 600), (999, 999)],
                default=scarletbanner.wiki.enums.PermissionLevel["PUBLIC"],
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="write",
            field=models.IntegerField(
                choices=[(100, 100), (300, 300), (600, 600), (999, 999)],
                default=scarletbanner.wiki.enums.PermissionLevel["PUBLIC"],
            ),
        ),
    ]
