# Generated by Django 5.0.6 on 2024-06-01 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wiki", "0004_alter_historicalpage_read_alter_historicalpage_write_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"base_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="historicalpage",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
