# Generated by Django 5.0.6 on 2024-06-01 23:53

import django.db.models.deletion
import scarletbanner.wiki.enums
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wiki", "0007_historicalpage_parent_page_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpage",
            name="read",
            field=models.IntegerField(
                choices=[
                    (100, "Public"),
                    (300, "Members only"),
                    (600, "Editors only"),
                    (900, "Owners only"),
                    (999, "Administrator only"),
                ],
                default=scarletbanner.wiki.enums.PermissionLevel["PUBLIC"],
            ),
        ),
        migrations.AlterField(
            model_name="historicalpage",
            name="write",
            field=models.IntegerField(
                choices=[
                    (100, "Public"),
                    (300, "Members only"),
                    (600, "Editors only"),
                    (900, "Owners only"),
                    (999, "Administrator only"),
                ],
                default=scarletbanner.wiki.enums.PermissionLevel["PUBLIC"],
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="read",
            field=models.IntegerField(
                choices=[
                    (100, "Public"),
                    (300, "Members only"),
                    (600, "Editors only"),
                    (900, "Owners only"),
                    (999, "Administrator only"),
                ],
                default=scarletbanner.wiki.enums.PermissionLevel["PUBLIC"],
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="write",
            field=models.IntegerField(
                choices=[
                    (100, "Public"),
                    (300, "Members only"),
                    (600, "Editors only"),
                    (900, "Owners only"),
                    (999, "Administrator only"),
                ],
                default=scarletbanner.wiki.enums.PermissionLevel["PUBLIC"],
            ),
        ),
        migrations.CreateModel(
            name="HistoricalOwnedPage",
            fields=[
                (
                    "page_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="wiki.page",
                    ),
                ),
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=1024)),
                ("body", models.TextField()),
                (
                    "read",
                    models.IntegerField(
                        choices=[
                            (100, "Public"),
                            (300, "Members only"),
                            (600, "Editors only"),
                            (900, "Owners only"),
                            (999, "Administrator only"),
                        ],
                        default=scarletbanner.wiki.enums.PermissionLevel["PUBLIC"],
                    ),
                ),
                (
                    "write",
                    models.IntegerField(
                        choices=[
                            (100, "Public"),
                            (300, "Members only"),
                            (600, "Editors only"),
                            (900, "Owners only"),
                            (999, "Administrator only"),
                        ],
                        default=scarletbanner.wiki.enums.PermissionLevel["PUBLIC"],
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="wiki.page",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical owned page",
                "verbose_name_plural": "historical owned pages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OwnedPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wiki.page",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("wiki.page",),
        ),
    ]
